### ISSUE TITLE
Traverse dictionary at a given level

### ISSUE THREAD

**Issue by stanleyjs** [fabiocaccamo/python-benedict#72] opened 2022-01-09 04:50 UTC
Hi,

I would like to iterate over all of the keys / items of a given level.

Ideal behavior:

```
d=benedict()
d['a'][0] = 0
d['a'][1] = 1
d['b'] = 0

print(d.keypaths(level=0))
>>> ['a','b']
print(d.keypaths(level=1))
>>>['a.0','a.1']
```
And similar functionality for items and other iterators...

**Comment by fabiocaccamo** [comment] 2022-03-01 14:38
Duplicate of #49, improving the traverse method a `level` and `max_depth` options could be added.

**Closed by fabiocaccamo** 2022-03-01 14:38 UTC
Labels: duplicate, enhancement
