### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by alexespencer** [fabiocaccamo/python-benedict#39] opened 2020-09-30 11:47 UTC
**Python version**
3.7

**Package version**
0.18.0 vs 0.21.0

**Current behavior (bug description)**
0.21.0 is up to 30 times slower in some instances than 0.18.0 for "large" dictionaries

**Expected behavior**
Performance is equal or better in 0.21.0

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/7407677/94681274-10747500-031b-11eb-8119-5c54cb3f311d.png)

Code to reproduce:
import benedict
from benedict import benedict as ben
import logging
import os
logger = logging.getLogger(os.path.basename(__file__))
logger.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s : [%(levelname)s] : %(name)s : %(message)s')
log_file_handler = logging.StreamHandler()
log_file_handler.setFormatter(formatter)
logger.addHandler(log_file_handler)

# Create large nested dictionary

test = ben({})

logger.info(f"Starting test with python-benedict version: {benedict.__version__}")
for i in range(0, 500):
    for j in range(0, 100):
        test.set(f"{i}.{j}", f"text-{i}-{j}")

# Access multiple elements with a few missing element paths
for i in range(0, 550):
    for j in range(0, 110):
        test.get(f"{i}.{j}", None)

logger.info("End")

**Comment by alexespencer** [comment] 2020-09-30 11:49
In the screenshot above, you can see that 0.21.0 took 60 seconds ish to run. The 0.18.0 code took just 2 seconds. Code to reproduce this is attached above. I just used python 3.7, and in two different environs had 0.21.0 and 0.18.0. This was spotted during a huge performance slow down in our kubernetes cluster - I have now locked the version (should have done that before, that's on me) - but thought you would want to know about this in case it's fixable.

**Comment by alexespencer** [comment] 2020-09-30 12:28
I removed the "get" of missing elements and it still takes a long time - I wondered if it might just be that bit that's slow, but it still took the same time. Ideally the timer would only start after the dictionary has been created too - so I reran the test and 0.21.0 took 30 seconds - so perhaps both setting and getting is affected?

**Comment by fabiocaccamo** [comment] 2020-09-30 12:46
@alexespencer thank you for reporting this, I'm confident that this slowdown is caused by the base layer introduced [here](https://github.com/fabiocaccamo/python-benedict/commit/eac655b67f1a366dd37b49edaa73ef2065689d52).

**Comment by alexespencer** [comment] 2020-09-30 12:47
@fabiocaccamo was that from 0.20.0? I just double checked 0.19.0 and that's all good, the slow down starts from 0.20.0

**Comment by fabiocaccamo** [comment] 2020-09-30 12:50
Yes, it has been released in `0.20.0`, you pass an initial dict or you start with an empty dict?

**Comment by alexespencer** [comment] 2020-09-30 13:02
@fabiocaccamo in the test code above I start with an empty one, passing "benedict({})" to initialise it, then populate via .set. However, in our production code we usually read JSON into a dict, then pass that in.

**Comment by fabiocaccamo** [comment] 2020-09-30 16:38
@alexespencer I figured out the problem, it is the [automatic casting](https://github.com/fabiocaccamo/python-benedict/blob/master/benedict/dicts/__init__.py#L56) to `benedict` of retrieved dict values.

The problem occurs because some internal utilities call methods like `__getitem__` or `get` (for example [this one](https://github.com/fabiocaccamo/python-benedict/blob/master/benedict/dicts/keylist/keylist_util.py#L18)) that potentially could return dict values that will be casted to `benedict`.

**Comment by fabiocaccamo** [comment] 2020-09-30 17:06
@alexespencer You can upgrade to `0.21.1` version.

**Closed** 2020-09-30 17:08 UTC
Labels: bug
