### ISSUE TITLE
setting value on path with an index doesn't create the list element

### ISSUE THREAD

**Issue by ponders** [fabiocaccamo/python-benedict#41] opened 2020-11-23 21:06 UTC
**Python version**
3.8.1

**Package version**
0.22.0

**Current behavior (bug description)**
d[x[0].y] = value
  throws an exception if x[0] doesn't exist

**Expected behavior**
d[x[0].y] = value
  I expected that the list element 0 would be automatically created (i.e. like a key is) if it don't exist

**Comment by fabiocaccamo** [comment] 2020-11-25 10:07
- if `x` is a `list` and not a `benedict` instance this problem has nothing to do with `benedict`.
- if `x[0].y` is a keypath, you wrote it wrong.
- If you would like to append items to a list inside a `benedict` instance, this is a duplicate of #27.

**Closed by fabiocaccamo** 2020-11-25 10:07 UTC
Labels: enhancement
